### ISSUE TITLE
Who is using Fizz Gateway？（欢迎使用 Fizz Gateway 的个人和公司在此留言）

### ISSUE THREAD

**Issue by linwaiwai** [fizzgate/fizz-gateway-node#9]
## Who is using Fizz Gateway？
Sincerely thank everyone who constantly keeps on using and supporting Fizz Gateway. We will try our best to make Fizz Gateway better and make the community and ecology more prosperous.
 
## The original intention of this issue
* We’d like to listen to the community to make Fizz better.
* We want to attract more partners to contribute to Fizz.
* Learn more about the practical use scenarios of Fizz to facilitate the next step of planning.
 
## What we expect from you
Please submit a comment in this issue to include the following information:
 
your company, school or organization.
your city and country.
your contact info: weibo, email, wechat (at least one).
for what business scenario do you use Fizz.
 
You can refer to the following sample answer:

```
* Organization: Fizz Gateway
* Location: GuangZhou, China
* Contact: 524423586@qq.com
* Purpose: as a API gateway to deal with east-west traffic between microservices.
```
 
Thanks again for your participation! Your support is the motivation for us to move forward.
Fizz Gateway community
 
## 谁在使用 Fizz Gateway？
感谢正在使用和关注 Fizz Gateway 的开发者，我们会持续投入，让 Fizz Gateway 项目和社区更加繁荣。
 
## 这个 issue 的出发点
* 聆听社区的声音，让 Fizz Gateway 解决实际的问题
* 吸引更多的开发者参与和贡献
* 更多的了解 Fizz Gateway 的实际使用场景，以便后续版本的计划

## 我们期待您能提供
在此提交一条评论, 评论内容包括:
 
您所在公司、学校或组织
您所在的城市、国家
您的联系方式: 微博、邮箱、微信 (至少一个)
您将 Fizz Gateway 用于哪些业务场景

可以参考下面的示例：
 
```
组织： Fizz Gateway
地点：中国广州
联系方式： 524423586@qq.com
使用场景：作为应用网关处理授权方面的问题
```
 
多谢您的支持！
 Fizz Gateway 社区

**Comment by TRAFALGARC** [comment]
组织:百胜互联
地点:中国上海
联系方式:2753302328@qq.com
使用场景:统一处理供应商接口

**Comment by linxiaowu345** [comment]
组织:亚美信息
地点:中国广东
联系方式:1476835876@qq.com
使用场景:应用网关安全授权
